// ── Países (label español, en para API de ciudades / propiedades HubSpot en inglés) ──
// Fuente única compartida entre RecordModal (ficha de empresa/deal) y AdminPage
// (asignación de países por operador), para evitar listas desincronizadas.
export const COUNTRIES = [
  { label: 'Alemania', en: 'Germany' },
  { label: 'Antigua y Barbuda', en: 'Antigua and Barbuda' },
  { label: 'Argentina', en: 'Argentina' },
  { label: 'Australia', en: 'Australia' },
  { label: 'Austria', en: 'Austria' },
  { label: 'Bahamas', en: 'Bahamas' },
  { label: 'Barbados', en: 'Barbados' },
  { label: 'Bélgica', en: 'Belgium' },
  { label: 'Bolivia', en: 'Bolivia' },
  { label: 'Brasil', en: 'Brazil' },
  { label: 'Bulgaria', en: 'Bulgaria' },
  { label: 'Canadá', en: 'Canada' },
  { label: 'Chile', en: 'Chile' },
  { label: 'China', en: 'China' },
  { label: 'Colombia', en: 'Colombia' },
  { label: 'Corea del Sur', en: 'South Korea' },
  { label: 'Costa Rica', en: 'Costa Rica' },
  { label: 'Croacia', en: 'Croatia' },
  { label: 'Cuba', en: 'Cuba' },
  { label: 'Dinamarca', en: 'Denmark' },
  { label: 'Dominica', en: 'Dominica' },
  { label: 'Ecuador', en: 'Ecuador' },
  { label: 'Egipto', en: 'Egypt' },
  { label: 'El Salvador', en: 'El Salvador' },
  { label: 'Emiratos Árabes Unidos', en: 'United Arab Emirates' },
  { label: 'Escocia', en: 'Scotland' },
  { label: 'Eslovaquia', en: 'Slovakia' },
  { label: 'España', en: 'Spain' },
  { label: 'Estados Unidos', en: 'United States' },
  { label: 'Etiopía', en: 'Ethiopia' },
  { label: 'Filipinas', en: 'Philippines' },
  { label: 'Finlandia', en: 'Finland' },
  { label: 'Francia', en: 'France' },
  { label: 'Georgia', en: 'Georgia' },
  { label: 'Ghana', en: 'Ghana' },
  { label: 'Granada', en: 'Grenada' },
  { label: 'Grecia', en: 'Greece' },
  { label: 'Guatemala', en: 'Guatemala' },
  { label: 'Guyana', en: 'Guyana' },
  { label: 'Haití', en: 'Haiti' },
  { label: 'Honduras', en: 'Honduras' },
  { label: 'Hungría', en: 'Hungary' },
  { label: 'India', en: 'India' },
  { label: 'Indonesia', en: 'Indonesia' },
  { label: 'Inglaterra', en: 'England' },
  { label: 'Irán', en: 'Iran' },
  { label: 'Iraq', en: 'Iraq' },
  { label: 'Irlanda', en: 'Ireland' },
  { label: 'Islandia', en: 'Iceland' },
  { label: 'Israel', en: 'Israel' },
  { label: 'Italia', en: 'Italy' },
  { label: 'Jamaica', en: 'Jamaica' },
  { label: 'Japón', en: 'Japan' },
  { label: 'Jordania', en: 'Jordan' },
  { label: 'Kazajistán', en: 'Kazakhstan' },
  { label: 'Kenia', en: 'Kenya' },
  { label: 'Malasia', en: 'Malaysia' },
  { label: 'Marruecos', en: 'Morocco' },
  { label: 'México', en: 'Mexico' },
  { label: 'Moldavia', en: 'Moldova' },
  { label: 'Nigeria', en: 'Nigeria' },
  { label: 'Noruega', en: 'Norway' },
  { label: 'Nueva Zelanda', en: 'New Zealand' },
  { label: 'Países Bajos', en: 'Netherlands' },
  { label: 'Pakistán', en: 'Pakistan' },
  { label: 'Panamá', en: 'Panama' },
  { label: 'Paraguay', en: 'Paraguay' },
  { label: 'Perú', en: 'Peru' },
  { label: 'Polonia', en: 'Poland' },
  { label: 'Portugal', en: 'Portugal' },
  { label: 'Puerto Rico', en: 'Puerto Rico' },
  { label: 'Qatar', en: 'Qatar' },
  { label: 'Reino Unido', en: 'United Kingdom' },
  { label: 'República Checa', en: 'Czech Republic' },
  { label: 'República Dominicana', en: 'Dominican Republic' },
  { label: 'Rumanía', en: 'Romania' },
  { label: 'Rusia', en: 'Russia' },
  { label: 'Arabia Saudita', en: 'Saudi Arabia' },
  { label: 'San Cristóbal y Nieves', en: 'Saint Kitts and Nevis' },
  { label: 'San Vicente y las Granadinas', en: 'Saint Vincent and the Grenadines' },
  { label: 'Santa Lucía', en: 'Saint Lucia' },
  { label: 'Serbia', en: 'Serbia' },
  { label: 'Singapur', en: 'Singapore' },
  { label: 'Sudáfrica', en: 'South Africa' },
  { label: 'Suecia', en: 'Sweden' },
  { label: 'Suiza', en: 'Switzerland' },
  { label: 'Tailandia', en: 'Thailand' },
  { label: 'Taiwán', en: 'Taiwan' },
  { label: 'Trinidad y Tobago', en: 'Trinidad and Tobago' },
  { label: 'Turquía', en: 'Turkey' },
  { label: 'Ucrania', en: 'Ukraine' },
  { label: 'Uruguay', en: 'Uruguay' },
  { label: 'Venezuela', en: 'Venezuela' },
  { label: 'Vietnam', en: 'Vietnam' },
]

export const COUNTRY_LABELS = COUNTRIES.map(c => c.label)
export const COUNTRY_EN_BY_LABEL = Object.fromEntries(COUNTRIES.map(c => [c.label, c.en]))
